### PR TITLE
[T-6679][15.0][ADD] project_task_description_template_section

### PR DESCRIPTION
**Pull request by Tisho99**

### CODE REVIEW

**Comment by Tisho99** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Works fine in an empty database 👍, but some comments:

- IMO the module name is too generic. Why don't you use project_task_description_template_section or something similar? Doesn't a name like that match better its functionallities?

- Are you sure you don't want to make this for the OCA? I think it can be useful. Maybe I can ping a couple of users and ask their opinion about the idea of porting the module to de OCA.

Let me know your feedback @Tisho99 and @ValentinVinagre

**Comment by Tisho99** [comment]
@HaraldPanten 

I see correct the change in the name.

I also think this would be useful for oca, but doing it for Sygel was Valentin's decision.

CC @ValentinVinagre

**Comment by ValentinVinagre** [comment]
@HaraldPanten @Tisho99 I think the name change of the module is correct.
On the other hand, for the moment I would not take it to OCA, we can see if we do it on the OCA Spanish Days

**Comment by HaraldPanten** [comment]
OK. Changing the name is enough

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten 

I uploaded the requested changes. 

The PR is ready to be merged

**Comment by HaraldPanten** [comment]
What about the PR title and the commit message?

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
